export const data = [
  {
    name: "Page A",
    uv: 60,
    pv: 400,
    amt: 24,
  },
  {
    name: "Page B",
    uv: 80,
    pv: 700,
    amt: 22,
  },
  {
    name: "Page C",
    uv: 2000,
    pv: 400,
    amt: 2290,
  },
  {
    name: "Page D",
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "Page E",
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "Page F",
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Page G",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];

export const tickets = [
  {
    img: "/customer-1.jpg",
    desc: "Contact email not linked",
    updated: "2 days ago",
    name: "Tom cruise",
    date: "19 May 2023",
    time: "7:32 AM",
    priority: "High",
  },
  {
    img: "/customer-2.jpg",
    desc: "Adding images to featured posts",
    updated: "4 hours ago",
    name: "Robert Downey",
    date: "22 May 2023",
    time: "6:32 AM",
    priority: "Normal",
  },
  {
    img: "/customer-3.jpg",
    desc: "When will i be charged this month?",
    updated: "4 hours ago",
    name: "Matt Damon",
    date: "22 May 2023",
    time: "6:32 AM",
    priority: "Low",
  },
  {
    img: "/customer-4.jpg",
    desc: "Payment not going through",
    updated: "4 hours ago",
    name: "Hery Cavil",
    date: "28 May 2023",
    time: "6:30 AM",
    priority: "Normal",
  },
  {
    img: "/customer-5.jpg",
    desc: "Downtime since last week",
    updated: "4 hours ago",
    name: "Christian Bale",
    date: "28 May 2023",
    time: "6:30 AM",
    priority: "High",
  },
  {
    img: "/customer-6.jpg",
    desc: "Unable to add replies",
    updated: "4 days ago",
    name: "Chris Evans",
    date: "28 May 2023",
    time: "6:30 AM",
    priority: "Low",
  },
  {
    img: "/ben.jpg",
    desc: "Unable to change password",
    updated: "4 days ago",
    name: "Sam smith",
    date: "28 May 2023",
    time: "6:30 AM",
    priority: "High",
  },
  {
    img: "/steve.jpg",
    desc: "Referral Bonus",
    updated: "28 days ago",
    name: "Steve Rogers",
    date: "19 May 2023",
    time: "6:30 AM",
    priority: "Normal",
  },
];
